name: postgres_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using PostgreSQL
version: 0.0.9+2
homepage: https://github.com/cachapa/postgres_crdt
repository: https://github.com/cachapa/postgres_crdt
issue_tracker: https://github.com/cachapa/postgres_crdt/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  postgres: ^2.6.1
  sql_crdt: ^0.0.9+1

dev_dependencies:
  lints: any
  test: any
