name: sqlite_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using Sqlite as storage
version: 0.0.6
homepage: https://github.com/cachapa/sqlite_crdt
repository: https://github.com/cachapa/sqlite_crdt
issue_tracker: https://github.com/cachapa/sqlite_crdt/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  sqflite_common: ^2.4.1
  sqflite_common_ffi: ^2.2.1
  sqlparser: ^0.26.0
  uuid: ^3.0.7

dev_dependencies:
  lints: any
  test: any
