name: postgres_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using PostgreSQL
version: 1.0.3
homepage: https://github.com/cachapa/postgres_crdt
repository: https://github.com/cachapa/postgres_crdt
issue_tracker: https://github.com/cachapa/postgres_crdt/issues

environment:
  sdk: '^3.0.0'

dependencies:
  postgres: ^2.6.1
  sql_crdt: ^1.0.3
#    path: ../sql_crdt

dev_dependencies:
  lints: any
  test: any
