name: postgres_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using PostgreSQL
version: 0.0.7
homepage: https://github.com/cachapa/sql_crdt
repository: https://github.com/cachapa/sql_crdt
issue_tracker: https://github.com/cachapa/sql_crdt/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  postgres: ^2.5.2
  sql_crdt: ^0.0.7

dev_dependencies:
  lints: any
  test: any
