name: sqlite_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using Sqlite
version: 0.0.8+1
homepage: https://github.com/cachapa/sql_crdt
repository: https://github.com/cachapa/sql_crdt
issue_tracker: https://github.com/cachapa/sql_crdt/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  sqflite_common: ^2.4.3
  sqflite_common_ffi: ^2.2.2
  sql_crdt: ^0.0.8+1
  sqflite_common_ffi_web: ^0.3.3+2

dev_dependencies:
  lints: any
  test: any
  uuid: ^3.0.7
