name: Publish to pub.dev

on:
  release:
    types: [ published ]

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load credentials
        run: |
          mkdir -p ~/.pub-cache 
          echo '${{ secrets.CREDENTIALS_JSON }}' > ~/.pub-cache/credentials.json

      - name: Publish package
        run: dart pub publish -f
