name: Publish to pub.dev

on:
  push:
    branches: [ "master" ]

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load credentials
        run: |
          mkdir -p ~/.pub-cache 
          cat '${{ secrets.CREDENTIALS_JSON }}' > ~/.pub-cache/credentials.json

      - name: Publish package
        run: dart pub publish -f
