name: Quality Gate [Postgres]

on:
  push:
    branches:
      - '**'

defaults:
  run:
    working-directory: postgres_crdt

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1

      - name: Verify code formatting
        run: dart format --output none --set-exit-if-changed .

      - name: Get dependencies
        run: dart pub get

      - name: Static code analysis
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart run test

